INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),1,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),1,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),1,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),1,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),1,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),2,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),2,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),2,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),2,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),2,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),3,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),3,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),3,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),3,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),3,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),4,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),4,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),4,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),4,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),4,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),5,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),5,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),5,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),5,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),5,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),6,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),6,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),6,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),6,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),6,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),7,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),7,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),7,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),7,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),7,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),8,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),8,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),8,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),8,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),8,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),9,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),9,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),9,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),9,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),9,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),10,'W ciągu 7 dni odbierz klucze go głównego kontenera na śmieci','Odbierz klucze', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),10,'Masz tydzień na zgłoszenie odbioru technicznego instalacji wodnej i energetyczne w mieszkaniu','Zgłoś odbiór instalacji', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),10,'Opłać kaucję w wysokości trzykrotności czynszu w ciągu 30 dni od zarejestrowania w aplikacji myFlat','Opłać kaucję', (DATE_ADD(localtimestamp(), INTERVAL 30 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),10,'Wszystkie dokumenty zwiazane z wynajmem mieszkania zostaną wysłane do Ciebie drogą mailową. Prosze potwierdź ich otrzymanie za pomocą platformy autenti.com','Sprawdź skrzynkę e-mail', (DATE_ADD(localtimestamp(), INTERVAL 7 DAY)), localtimestamp(), 'ACTIVE', true);
INSERT INTO tasks(created_at,owner_id, description, title, deadline, start_date, status, active) VALUES (localtime(),10,'Zarejestruj się na osiedlowym forum naszaosiedle.org i przywitaj się z sąsiadami','Przywitaj się', (DATE_ADD(localtimestamp(), INTERVAL 14 DAY)), localtimestamp(), 'ACTIVE', true);

